### ISSUE TITLE
Release v5.0.0-rc.4 has issues

### ISSUE THREAD

**Issue by vTechGIS** [Akylas/mobile-sdk#2]
I appreciate your efforts to maintain this library, it's a great library.

In the v5.0.0-rc.4 release I see the carto-mobile-sdk-android-5.0.0-rc.4.aar file is only 643 KB

Do you have any documentation on setting up an environment to develop the library? I want to contribute but I can't deploy the environment yet. 

Thank you very much

**Comment by farfromrefug** [comment]
@vTechGIS I know what happened I commented something for tests and I forgot to uncomment while testing github ci :s really sorry will try to fix it soon

**Comment by farfromrefug** [comment]
@vTechGIS should be good now. Let me know if you have any issue. 
I ll look at releasing using jitpack.io

**Comment by vTechGIS** [comment]
> @vTechGIS should be good now. Let me know if you have any issue. I ll look at releasing using jitpack.io

Thank you, I tested, the build works fine
